spring:
  application:
    name: luoli-server
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

cos:
  secretId: AKIDqlYlkVQZsv1iJgJfRzHceYGjuRlsskpS
  secretKey: C9qLK8gzJekgJfLlwBKEwN7k7ylJabrt
  durationSeconds: 1800
  bucket: luolibucket-1300744339
  region: ap-guangzhou
  allowPrefix: '*'
  path: https://luolibucket-1300744339.cos.ap-guangzhou.myqcloud.com
  prefix: scenicspots

rocketmq:
  accessKey: LTAI4GJcGuu2J6jKUvL9ijim
  secretKey: fsabNFCULydgaYQFGOnnuqe0jswXD5
  nameSrvAddr: http://MQ_INST_1186863933821322_BXaPzrkg.mq-internet-access.mq-internet.aliyuncs.com:80
  topic: luoli-topic2
  groupId: GID_002
  tag: '*'

wx:
  appid: wx5e7b6ac7acadb5a3
  secret: 5ac0a74aba9a4eebbdea7da298a6fceb
  tokenUrl: https://api.weixin.qq.com/cgi-bin/token
  codeUrl: https://api.weixin.qq.com/cgi-bin/wxaapp/createwxaqrcode


hl:
  error:
    code: [3,003,1001,1002,1003,1008]
