spring:
  application:
    name: luoli-server
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

cos:
  secretId: 11111111111111
  secretKey: 111111111111
  durationSeconds: 1800
  bucket: 1111111111
  region: 111
  allowPrefix: '*'
  path: 1111
  prefix: 11

rocketmq:
  accessKey: 111
  secretKey: 11
  nameSrvAddr: 1111
  topic: 111
  groupId: 111
  tag: '*'

wx:
  appid: wx5e7b6ac7acadb5a3
  secret: 5ac0a74aba9a4eebbdea7da298a6fceb
  tokenUrl: https://api.weixin.qq.com/cgi-bin/token
  codeUrl: https://api.weixin.qq.com/cgi-bin/wxaapp/createwxaqrcode


hl:
  error:
    code: [3,003,1001,1002,1003,1008]
